package com.example.nammashaaleinventory.ui.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.nammashaaleinventory.data.local.entities.AssetEntity
import com.example.nammashaaleinventory.data.repository.InventoryRepository
import com.example.nammashaaleinventory.util.Advisory
import com.example.nammashaaleinventory.util.AdvisoryEngine
import com.example.nammashaaleinventory.util.PreferenceManager
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

data class DashboardUiState(
    val totalAssets: Int = 0,
    val workingCount: Int = 0,
    val needsRepairCount: Int = 0,
    val brokenCount: Int = 0,
    val lostCount: Int = 0,
    val advisories: List<Advisory> = emptyList(),
    val schoolName: String = ""
)

class DashboardViewModel(
    private val repository: InventoryRepository,
    private val preferenceManager: PreferenceManager
) : ViewModel() {

    val uiState: StateFlow<DashboardUiState> = combine(
        repository.allAssets,
        repository.pendingRepairs,
        repository.allIssues,
        preferenceManager.schoolName
    ) { assets, repairs, issues, schoolName ->
        val lastAudit = assets.maxByOrNull { it.lastCheckedDate }?.lastCheckedDate
        
        DashboardUiState(
            totalAssets = assets.size,
            workingCount = assets.count { it.status == "WORKING" },
            needsRepairCount = assets.count { it.status == "NEEDS_REPAIR" },
            brokenCount = assets.count { it.status == "BROKEN" },
            lostCount = assets.count { it.status == "LOST" },
            advisories = AdvisoryEngine.generateAdvisories(assets, repairs, issues, lastAudit),
            schoolName = schoolName
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5000),
        initialValue = DashboardUiState()
    )

    fun generateReport(): String {
        val state = uiState.value
        return """
            Namma-Shaale Inventory Report
            School: ${state.schoolName}
            Date: ${java.text.SimpleDateFormat("dd/MM/yyyy", java.util.Locale.getDefault()).format(java.util.Date())}
            
            Inventory Summary:
            -----------------
            Total Assets: ${state.totalAssets}
            Working: ${state.workingCount}
            Needs Repair: ${state.needsRepairCount}
            Broken: ${state.brokenCount}
            Lost: ${state.lostCount}
            
            This report was generated by the Namma-Shaale Digital Asset Auditor.
        """.trimIndent()
    }

}

class DashboardViewModelFactory(
    private val repository: InventoryRepository,
    private val preferenceManager: PreferenceManager
) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(DashboardViewModel::class.java)) {
            @Suppress("UNCHECKED_CAST")
            return DashboardViewModel(repository, preferenceManager) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}
