package com.example.nammashaaleinventory.util

import com.example.nammashaaleinventory.data.local.entities.AssetEntity
import com.example.nammashaaleinventory.data.local.entities.IssueLogEntity
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ReportBuilder {
    fun generatePlainTextReport(
        schoolName: String,
        assets: List<AssetEntity>,
        issues: List<IssueLogEntity>,
        advisories: List<Advisory>
    ): String {
        val dateFormat = SimpleDateFormat("dd/MM/yyyy HH:mm", Locale.getDefault())
        val date = dateFormat.format(Date())

        val sb = StringBuilder()
        sb.append("NAMMA-SHAALE INVENTORY REPORT\n")
        sb.append("=============================\n")
        sb.append("School: $schoolName\n")
        sb.append("Date: $date\n\n")

        sb.append("SUMMARY STATS\n")
        sb.append("-------------\n")
        sb.append("Total Assets: ${assets.size}\n")
        sb.append("Working: ${assets.count { it.status == "WORKING" }}\n")
        sb.append("Needs Repair: ${assets.count { it.status == "NEEDS_REPAIR" }}\n")
        sb.append("Broken: ${assets.count { it.status == "BROKEN" }}\n")
        sb.append("Lost: ${assets.count { it.status == "LOST" }}\n\n")

        sb.append("CATEGORIES\n")
        sb.append("----------\n")
        assets.groupBy { it.category }.forEach { (category, list) ->
            sb.append("- $category: ${list.size}\n")
        }
        sb.append("\n")

        sb.append("TOP ISSUES (RECENT)\n")
        sb.append("------------------\n")
        issues.take(10).forEach { issue ->
            val assetName = assets.find { it.id == issue.assetId }?.name ?: "Unknown"
            sb.append("- [${issue.issueType}] $assetName: ${issue.description}\n")
        }
        if (issues.isEmpty()) sb.append("No issues logged.\n")
        sb.append("\n")

        sb.append("SMART ADVISORIES\n")
        sb.append("----------------\n")
        advisories.forEach { advisory ->
            sb.append("! ${advisory.title}: ${advisory.message}\n")
        }
        sb.append("\n")

        sb.append("Generated by Namma-Shaale Inventory App (Offline-First)\n")
        
        return sb.toString()
    }
}
